apiVersion: v1
kind: Service
metadata:
  name: ekow-svc
spec:
  selector:
    app: ekow-api  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
 
--- 
apiVersion: v1
kind: Service
metadata:
  name: redis-svc 
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

